version: "3.8"
services:
  db:
    image: mysql:8.0.22
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./env/db.env
      - ./env/wp.env
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    # カスタムDockerfileを指定
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/wordpress
    env_file:
      - ./env/wp.env
    tty: true
    depends_on:
      - db

volumes:
  db_data:
